export type Product = {
    product_id: string;
    name: string;
    description: string | null;
    meta_title: string;
    meta_description: string;
    meta_keyword: string;
    tag: string;
    model: string;
    sku: string;
    upc: string;
    ean: string;
    jan: string;
    isbn: string;
    mpn: string;
    location: string;
    quantity: string;
    stock_status: string;
    image: boolean;
    manufacturer_id: string;
    manufacturer: string;
    price: number;
    special: string;
    reward: string;
    points: string;
    tax_class_id: string;
    date_available: number;
    weight: number;
    weight_class_id: string;
    length: number;
    length_class_id: string;
    width: number;
    height: number;
    subtract: number;
    rating: string;
    reviews: number;
    minimum: string;
    sort_order: number;
    status: boolean;
    date_added: string;
    date_modified: string;
    viewed: number | null;
    slug: string;
};

export type GetProductResponse = Product;

export type GetProductsResponse = Product[];